# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSnapdealUser1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_snapdealUser1(self):
    self.driver.get("https://www.snapdeal.com/")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.CSS_SELECTOR, "#category3Data p:nth-child(12) .headingText").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cartTextSpan").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close-popup-icon > .sd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, "#category2Data > .leftData .shiftHeadTop").click()
    self.driver.execute_script("window.scrollTo(0,2201)")
    self.driver.execute_script("window.scrollTo(0,3201)")
    self.driver.execute_script("window.scrollTo(0,2201)")
    self.driver.execute_script("window.scrollTo(0,1101)")
    self.driver.execute_script("window.scrollTo(0,901)")
    self.driver.find_element(By.CSS_SELECTOR, "#category2Data > .leftData p:nth-child(2) .linkTest").click()
    self.driver.execute_script("window.scrollTo(0,2201)")
    self.driver.execute_script("window.scrollTo(0,1901)")
    self.driver.execute_script("window.scrollTo(0,1301)")
    self.driver.execute_script("window.scrollTo(0,801)")
    self.driver.find_element(By.CSS_SELECTOR, ".filter-inner:nth-child(3) > .filters-list:nth-child(2) > label").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".filter-section:nth-child(5) .sdCheckbox:nth-child(1) > label").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "#\\35 764608188178805245 .wooble").click()
    self.vars["win9208"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win9208"])
    self.driver.execute_script("window.scrollTo(0,491)")
    self.driver.find_element(By.LINK_TEXT, "Ratings & Reviews").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".active > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active > img").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".active > img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".emi-optn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bank-tab:nth-child(5) > span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close1").click()
    self.driver.find_element(By.ID, "add-cart-button-id").click()
    self.driver.find_element(By.CSS_SELECTOR, ".open-cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close-popup-icon > .sd-icon").click()
  
