# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSnapdealUser2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_snapdealUser2(self):
    self.driver.get("https://www.snapdeal.com/")
    self.driver.set_window_size(1382, 744)
    self.driver.execute_script("window.scrollTo(0,406)")
    self.driver.find_element(By.CSS_SELECTOR, "#category2Data > .leftData .shiftHeadTop").click()
    self.driver.execute_script("window.scrollTo(0,2850)")
    self.driver.find_element(By.LINK_TEXT, "Smartphones").click()
    self.driver.execute_script("window.scrollTo(0,2601)")
    self.driver.execute_script("window.scrollTo(0,2001)")
    self.driver.execute_script("window.scrollTo(0,701)")
    self.driver.find_element(By.CSS_SELECTOR, ".filter-section:nth-child(5) .filters-list:nth-child(1) > label").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, "#\\36 917529681328086912 .center").click()
    self.driver.find_element(By.CSS_SELECTOR, ".prodDetailBtn").click()
    self.driver.execute_script("window.scrollTo(0,837)")
    self.driver.find_element(By.ID, "add-cart-button-id").click()
    self.driver.find_element(By.CSS_SELECTOR, ".open-cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close-popup-icon > .sd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".open-cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".remove-item-shortlist").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close-popup-icon > .sd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close-popup-icon > .sd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, "#category2Data > .leftData p:nth-child(2) .linkTest").click()
    self.driver.find_element(By.CSS_SELECTOR, ".filter-inner:nth-child(3) > .filters-list:nth-child(2) > label").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".filter-section:nth-child(5) .sdCheckbox:nth-child(1) > label").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, "#\\35 764608188178805245 .center").click()
    self.driver.find_element(By.CSS_SELECTOR, ".prodDetailBtn").click()
    self.driver.execute_script("window.scrollTo(0,400)")
    self.driver.execute_script("window.scrollTo(0,300)")
    self.driver.execute_script("window.scrollTo(0,147)")
    self.driver.find_element(By.CSS_SELECTOR, ".active > img").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(3) > img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#add-cart-button-id > .intialtext").click()
    self.driver.find_element(By.CSS_SELECTOR, ".open-cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close-popup-icon > .sd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cartQuantity").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close-popup-icon > .sd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".price:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".price:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".price:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".price:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".price:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".price:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".price:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".price:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".price:nth-child(1)").click()
  
